#!/usr/bin/env bash

all_dirs="$(fdfind  -d 1 -t d --search-path $HOME/dev)"
all_dirs="$(fdfind  -d 1 -t d --search-path $HOME "configs|bin") "$all_dirs
selected=$(echo $all_dirs | sed "s/ /\n/g" | fzf)

if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename $selected | tr ".,: " "____")

switch_to() {
    if [[ -z "$TMUX" ]]; then
        tmux attach-session -t $selected_name
    else
        tmux switch-client -t $selected_name
    fi
}

if tmux has-session -t="$selected_name"; then
    switch_to
    exit 0
fi

tmux new-session -ds $selected_name -c $selected
tmux send-keys -t $selected_name "tmux-setup-session "
switch_to
