#!/usr/bin/env bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias c='clear'
alias e='exit'
alias t='tmux a'
alias vim='nvim'
alias gs='git status'
alias ga='git add'
alias gd='git diff'
alias gdc='git diff --cached'
alias gp='git pull'
alias gl='git log --oneline'

bind '"\ef":"tmux-find-session"'

if [[ -e ~/.bash_alias_local ]]; then
    source ~/.bash_alias_local
fi
